version: 0.2
phases:
 install:
   runtime-versions:
     nodejs: 12
   commands:
     - echo "install step"
     - yarn install
 pre_build:
   commands:
     - echo "pre_build step"
     # - npm test
 build:
   commands:
     - npm run-script build
 post_build:
   commands:
     - echo "post_build step"
     - ls ./build
     # - zip -r build.zip build/
artifacts:
  base-directory: build
  files:
    - '**/*'
cache:
  paths: 
    - node_modules/**/*