export const CALCULATE_BRIDGES = 'CALCULATE_BRIDGES';
export const SELECT_BRIDGE = 'SELECT_BRIDGE';
export const CALCULATE_CALENDAR = 'CALCULATE_CALENDAR';
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const ADD_CUSTOM_HOLIDAY = 'ADD_CUSTOM_HOLIDAY';