export const CALCULATE_BRIDGES = 'CALCULATE_BRIDGES';
export const SELECT_BRIDGE = 'SELECT_BRIDGE';
export const CALCULATE_CALENDAR = 'CALCULATE_CALENDAR';
export const CALCULATE_SETTINGS = 'CALCULATE_SETTINGS';